/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.g13;

import static com.mycompany.g13.SystemClass.givenOrder;

/**
 *
 * @author Admin
 */
public class star extends javax.swing.JFrame {
    
    /**
     * Creates new form star
     */
    public star() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        smallcoffestar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        smallcoffestar1 = new javax.swing.JButton();
        smallcoffestar2 = new javax.swing.JButton();
        smallcoffestar3 = new javax.swing.JButton();
        smallcoffestar4 = new javax.swing.JButton();
        smallcoffestar5 = new javax.swing.JButton();
        smallcoffestar6 = new javax.swing.JButton();
        smallcoffestar7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YILDIZLI ÜRÜNLER");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee-cup.png"))); // NOI18N
        jLabel1.setText("KÜÇÜK BOY İÇECEK");

        smallcoffestar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar.setText("10");
        smallcoffestar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee-cup.png"))); // NOI18N
        jLabel2.setText("ORTA BOY İÇECEK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee-cup.png"))); // NOI18N
        jLabel3.setText("BÜYÜK BOY İÇECEK");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee-bean.png"))); // NOI18N
        jLabel4.setText("100 gr Paket Kahve");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookie.png"))); // NOI18N
        jLabel5.setText("COOKİE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandwich.png"))); // NOI18N
        jLabel6.setText("SANDVİÇ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thermos.png"))); // NOI18N
        jLabel7.setText("TERMOS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mug.png"))); // NOI18N
        jLabel8.setText("KUPA");

        smallcoffestar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar1.setText("20");
        smallcoffestar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar1ActionPerformed(evt);
            }
        });

        smallcoffestar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar2.setText("30");
        smallcoffestar2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar2ActionPerformed(evt);
            }
        });

        smallcoffestar3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar3.setText("50");
        smallcoffestar3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar3ActionPerformed(evt);
            }
        });

        smallcoffestar4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar4.setText("200");
        smallcoffestar4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar4ActionPerformed(evt);
            }
        });

        smallcoffestar5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar5.setText("500");
        smallcoffestar5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar5ActionPerformed(evt);
            }
        });

        smallcoffestar6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar6.setText("60");
        smallcoffestar6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar6ActionPerformed(evt);
            }
        });

        smallcoffestar7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smallcoffestar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N
        smallcoffestar7.setText("300");
        smallcoffestar7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        smallcoffestar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallcoffestar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(smallcoffestar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(smallcoffestar2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(smallcoffestar4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(smallcoffestar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smallcoffestar5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallcoffestar3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallcoffestar6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallcoffestar7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(smallcoffestar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(smallcoffestar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallcoffestar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(smallcoffestar6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallcoffestar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(smallcoffestar5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(smallcoffestar4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(smallcoffestar7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void smallcoffestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestarActionPerformed
        // TODO add your handling code here:
        Drinks product = new Drinks("",0,"Yıldızlı Küçük Boy Kahve");
        product.setStar(10);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
        
    }//GEN-LAST:event_smallcoffestarActionPerformed

    private void smallcoffestar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar1ActionPerformed
        // TODO add your handling code here:
        Drinks product = new Drinks("",0,"Yıldızlı Orta Boy Kahve");
        product.setStar(20);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar1ActionPerformed

    private void smallcoffestar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar2ActionPerformed
        // TODO add your handling code here:
        Drinks product = new Drinks("",0,"Yıldızlı Büyük Boy Kahve");
        product.setStar(30);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar2ActionPerformed

    private void smallcoffestar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar4ActionPerformed
        // TODO add your handling code here:
        PacketedProducts product = new PacketedProducts("Yızldızlı Paket Kahve","",0);
        product.setStar(200);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar4ActionPerformed

    private void smallcoffestar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar3ActionPerformed
        // TODO add your handling code here:
        Food product = new Food("",0,"Yıldızlı Cookie", "501,9kcal");
        product.setStar(50);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar3ActionPerformed

    private void smallcoffestar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar6ActionPerformed
        // TODO add your handling code here:
        Food product = new Food("",0,"Yıldızlı Sandiviç", "244kcal");
        product.setStar(60);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar6ActionPerformed

    private void smallcoffestar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar5ActionPerformed
        // TODO add your handling code here:
        Gifts product = new Gifts(0,"Yıldızlı Termos", "Stanley");
        product.setStar(500);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar5ActionPerformed

    private void smallcoffestar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallcoffestar7ActionPerformed
        // TODO add your handling code here:
        Gifts product = new Gifts(0,"Yıldızlı Kupa", "Aladdin");
        product.setStar(300);
        SystemClass.add(product);
        CafeManagementGUI.order.setText(SystemClass.displayOrder(givenOrder));
    }//GEN-LAST:event_smallcoffestar7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new star().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton smallcoffestar;
    private javax.swing.JButton smallcoffestar1;
    private javax.swing.JButton smallcoffestar2;
    private javax.swing.JButton smallcoffestar3;
    private javax.swing.JButton smallcoffestar4;
    private javax.swing.JButton smallcoffestar5;
    private javax.swing.JButton smallcoffestar6;
    private javax.swing.JButton smallcoffestar7;
    // End of variables declaration//GEN-END:variables
}
